[project]
name = "youtube-mp3-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "certifi==2025.7.14",
    "charset-normalizer==3.4.2",
    "colorama==0.4.6",
    "decorator==4.4.2",
    "idna==3.10",
    "imageio==2.37.0",
    "imageio-ffmpeg==0.6.0",
    "moviepy==1.0.3",
    "numpy==2.3.1",
    "pillow==11.3.0",
    "proglog==0.1.12",
    "python-dotenv==1.1.1",
    "pytube==15.0.0",
    "requests==2.32.4",
    "tqdm==4.67.1",
    "urllib3==2.5.0",
    "yt-dlp==2025.6.30",
]
